# Generated by Django 4.2.10 on 2024-02-19 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('sign_up_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('add_date', models.DateField()),
                ('photo', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('add_date', models.DateField()),
                ('goods', models.ManyToManyField(to='market.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customers')),
            ],
        ),
    ]
