# Generated by Django 4.2.10 on 2024-02-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='sign_up_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='add_date',
            field=models.DateField(),
        ),
    ]
